// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using siapv_backend.DB;

#nullable disable

namespace siapv_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251204204558_EstadoFix_nullable_2")]
    partial class EstadoFix_nullable_2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("siapv_backend.DocGenerado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("cite_documento")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("id_documento")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("docGenerados");
                });

            modelBuilder.Entity("siapv_backend.Models.EstadoSolicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("estadoSolicitudes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            estado = "Designado"
                        },
                        new
                        {
                            Id = 2,
                            estado = "Solitado"
                        },
                        new
                        {
                            Id = 3,
                            estado = "Pendiente"
                        },
                        new
                        {
                            Id = 4,
                            estado = "Enviado a revisión"
                        },
                        new
                        {
                            Id = 5,
                            estado = "Aprobado"
                        },
                        new
                        {
                            Id = 6,
                            estado = "Finalizado"
                        });
                });

            modelBuilder.Entity("siapv_backend.Models.FuenteFinanciamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("fuenteFinanciamientos");
                });

            modelBuilder.Entity("siapv_backend.Models.LugarDestino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("destino")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("lugarDestinos");
                });

            modelBuilder.Entity("siapv_backend.Models.MediosTransporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("transporte")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.ToTable("mediosTransportes");
                });

            modelBuilder.Entity("siapv_backend.Models.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("proyectos");
                });

            modelBuilder.Entity("siapv_backend.Models.SolicitudViaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("citeId")
                        .HasColumnType("integer");

                    b.Property<string>("cite_memo")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("descripcion_viaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("empleadoId")
                        .HasColumnType("integer");

                    b.Property<int?>("estadoId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("fechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("fechaInicio")
                        .HasColumnType("date");

                    b.Property<int>("fuenteId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly?>("horaFin")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("horaInicio")
                        .HasColumnType("time without time zone");

                    b.Property<int>("lugarDestinoId")
                        .HasColumnType("integer");

                    b.Property<int?>("lugarOrigenId")
                        .HasColumnType("integer");

                    b.Property<int>("proyectoId")
                        .HasColumnType("integer");

                    b.Property<int?>("tipoViajeId")
                        .HasColumnType("integer");

                    b.Property<int?>("transporteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("citeId");

                    b.HasIndex("estadoId");

                    b.HasIndex("fuenteId");

                    b.HasIndex("lugarDestinoId");

                    b.HasIndex("lugarOrigenId");

                    b.HasIndex("proyectoId");

                    b.HasIndex("tipoViajeId");

                    b.HasIndex("transporteId");

                    b.ToTable("solicitudViajes");
                });

            modelBuilder.Entity("siapv_backend.Models.TipoViaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("tiposViaje");
                });

            modelBuilder.Entity("siapv_backend.Models.SolicitudViaje", b =>
                {
                    b.HasOne("siapv_backend.DocGenerado", "cite")
                        .WithMany()
                        .HasForeignKey("citeId");

                    b.HasOne("siapv_backend.Models.EstadoSolicitud", "estado")
                        .WithMany()
                        .HasForeignKey("estadoId");

                    b.HasOne("siapv_backend.Models.FuenteFinanciamiento", "fuente")
                        .WithMany()
                        .HasForeignKey("fuenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("siapv_backend.Models.LugarDestino", "lugarDestino")
                        .WithMany()
                        .HasForeignKey("lugarDestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("siapv_backend.Models.LugarDestino", "lugarOrigen")
                        .WithMany()
                        .HasForeignKey("lugarOrigenId");

                    b.HasOne("siapv_backend.Models.Proyecto", "proyecto")
                        .WithMany()
                        .HasForeignKey("proyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("siapv_backend.Models.TipoViaje", "tipoViaje")
                        .WithMany()
                        .HasForeignKey("tipoViajeId");

                    b.HasOne("siapv_backend.Models.MediosTransporte", "transporte")
                        .WithMany()
                        .HasForeignKey("transporteId");

                    b.Navigation("cite");

                    b.Navigation("estado");

                    b.Navigation("fuente");

                    b.Navigation("lugarDestino");

                    b.Navigation("lugarOrigen");

                    b.Navigation("proyecto");

                    b.Navigation("tipoViaje");

                    b.Navigation("transporte");
                });
#pragma warning restore 612, 618
        }
    }
}
