// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using siapv_backend.DB;

#nullable disable

namespace siapv_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251119213502_ViajesDoc")]
    partial class ViajesDoc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("siapv_backend.DocGenerado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("cite_documento")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("id_documento")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("docGenerados");
                });

            modelBuilder.Entity("siapv_backend.Models.Dependencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("createAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("dependenciaId")
                        .HasColumnType("integer");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("sigla")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("updateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Dependencia");
                });

            modelBuilder.Entity("siapv_backend.Models.EmpleadosContrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DenominacionCargo")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("DependenciaId")
                        .HasColumnType("integer");

                    b.Property<int?>("InmediatoSuperiorId")
                        .HasColumnType("integer");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("escalaSalarialId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("fechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("fechaFinContrato")
                        .HasColumnType("date");

                    b.Property<DateOnly>("fechaInicio")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("fecha_baja")
                        .HasColumnType("date");

                    b.Property<string>("nro_contrato")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<int>("personaId")
                        .HasColumnType("integer");

                    b.Property<NpgsqlTsVector>("searchCargo")
                        .IsRequired()
                        .HasColumnType("tsvector");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DependenciaId");

                    b.HasIndex("InmediatoSuperiorId");

                    b.HasIndex("escalaSalarialId");

                    b.HasIndex("personaId");

                    b.ToTable("EmpleadosContrato");
                });

            modelBuilder.Entity("siapv_backend.Models.EscalaSalarial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ResolucionEscalaId")
                        .HasColumnType("integer");

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("denominacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("haber_mensual")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("nivelSalarial")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("EscalaSalarial");
                });

            modelBuilder.Entity("siapv_backend.Models.FuenteFinanciamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("fuenteFinanciamientos");
                });

            modelBuilder.Entity("siapv_backend.Models.LugarDestino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("destino")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("lugarDestinos");
                });

            modelBuilder.Entity("siapv_backend.Models.MediosTransporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("transporte")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.ToTable("mediosTransportes");
                });

            modelBuilder.Entity("siapv_backend.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .HasColumnType("tsvector");

                    b.Property<string>("apellido_materno")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("apellido_paterno")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("carnet")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("celular")
                        .HasColumnType("integer");

                    b.Property<string>("complemento_carnet")
                        .HasColumnType("varchar(5)");

                    b.Property<bool>("completed")
                        .HasColumnType("boolean");

                    b.Property<string>("direccion")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("email_personal")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("fecha_nacimiento")
                        .HasColumnType("date");

                    b.Property<string>("localidad")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("nro_cel_referencia")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("nro_libreta_militar")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("parentezco")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("persona_referencia")
                        .HasColumnType("varchar(100)");

                    b.Property<char?>("sexo")
                        .HasColumnType("character(1)");

                    b.HasKey("Id");

                    b.ToTable("Persona");
                });

            modelBuilder.Entity("siapv_backend.Models.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("proyectos");
                });

            modelBuilder.Entity("siapv_backend.Models.SolicitudViaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("citeId")
                        .HasColumnType("integer");

                    b.Property<string>("cite_memo")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("descripcion_viaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("empleadoId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("fechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("fechaInicio")
                        .HasColumnType("date");

                    b.Property<int>("fuenteId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly?>("horaFin")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("horaInicio")
                        .HasColumnType("time without time zone");

                    b.Property<int>("lugarDestinoId")
                        .HasColumnType("integer");

                    b.Property<int>("lugarOrigenId")
                        .HasColumnType("integer");

                    b.Property<int>("proyectoId")
                        .HasColumnType("integer");

                    b.Property<int>("tipoViajeId")
                        .HasColumnType("integer");

                    b.Property<int>("transporteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("citeId");

                    b.HasIndex("empleadoId");

                    b.HasIndex("fuenteId");

                    b.HasIndex("lugarDestinoId");

                    b.HasIndex("lugarOrigenId");

                    b.HasIndex("proyectoId");

                    b.HasIndex("tipoViajeId");

                    b.HasIndex("transporteId");

                    b.ToTable("solicitudViajes");
                });

            modelBuilder.Entity("siapv_backend.Models.TipoViaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("tiposViaje");
                });

            modelBuilder.Entity("siapv_backend.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PersonaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.Property<bool?>("isActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("last_login")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.HasIndex(new[] { "username" }, "Index_UserName");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("siapv_backend.Models.EmpleadosContrato", b =>
                {
                    b.HasOne("siapv_backend.Models.Dependencia", "Dependencia")
                        .WithMany()
                        .HasForeignKey("DependenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("siapv_backend.Models.EmpleadosContrato", "InmediatoSuperior")
                        .WithMany()
                        .HasForeignKey("InmediatoSuperiorId");

                    b.HasOne("siapv_backend.Models.EscalaSalarial", "EscalaSalarial")
                        .WithMany()
                        .HasForeignKey("escalaSalarialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("siapv_backend.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("personaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dependencia");

                    b.Navigation("EscalaSalarial");

                    b.Navigation("InmediatoSuperior");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("siapv_backend.Models.SolicitudViaje", b =>
                {
                    b.HasOne("siapv_backend.DocGenerado", "cite")
                        .WithMany()
                        .HasForeignKey("citeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("siapv_backend.Models.EmpleadosContrato", "empleado")
                        .WithMany()
                        .HasForeignKey("empleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("siapv_backend.Models.FuenteFinanciamiento", "fuente")
                        .WithMany()
                        .HasForeignKey("fuenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("siapv_backend.Models.LugarDestino", "lugarDestino")
                        .WithMany()
                        .HasForeignKey("lugarDestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("siapv_backend.Models.LugarDestino", "lugarOrigen")
                        .WithMany()
                        .HasForeignKey("lugarOrigenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("siapv_backend.Models.Proyecto", "proyecto")
                        .WithMany()
                        .HasForeignKey("proyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("siapv_backend.Models.TipoViaje", "tipoViaje")
                        .WithMany()
                        .HasForeignKey("tipoViajeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("siapv_backend.Models.MediosTransporte", "transporte")
                        .WithMany()
                        .HasForeignKey("transporteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cite");

                    b.Navigation("empleado");

                    b.Navigation("fuente");

                    b.Navigation("lugarDestino");

                    b.Navigation("lugarOrigen");

                    b.Navigation("proyecto");

                    b.Navigation("tipoViaje");

                    b.Navigation("transporte");
                });

            modelBuilder.Entity("siapv_backend.Models.Usuario", b =>
                {
                    b.HasOne("siapv_backend.Models.Persona", "Persona")
                        .WithOne("Usuario")
                        .HasForeignKey("siapv_backend.Models.Usuario", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("siapv_backend.Models.Persona", b =>
                {
                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
