// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using siapv_backend.DB;

#nullable disable

namespace siapv_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251219195512_EstadoFix_reprogramacion")]
    partial class EstadoFix_reprogramacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("siapv_backend.DocGenerado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("cite_documento")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("id_documento")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("docGenerados");
                });

            modelBuilder.Entity("siapv_backend.Models.ActividadPOA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("codigo")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.ToTable("actividadPOAs");
                });

            modelBuilder.Entity("siapv_backend.Models.CategoriaProgramatica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("categoria")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("descripcion_categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("partida")
                        .HasColumnType("integer");

                    b.Property<double>("presupuesto_vigente")
                        .HasColumnType("double precision");

                    b.Property<double>("saldo")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("categoriasProgramaticas");
                });

            modelBuilder.Entity("siapv_backend.Models.CertificacionPOA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("actividadAcpId")
                        .HasColumnType("integer");

                    b.Property<int>("actividadAmpId")
                        .HasColumnType("integer");

                    b.Property<int>("correlativo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("gestion")
                        .HasColumnType("integer");

                    b.Property<int>("solicitudId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("actividadAcpId");

                    b.HasIndex("actividadAmpId");

                    b.HasIndex("solicitudId");

                    b.ToTable("certificacionPOAs");
                });

            modelBuilder.Entity("siapv_backend.Models.CertificacionPresupuestaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("categoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("concepto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("correlativo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("gestion")
                        .HasColumnType("integer");

                    b.Property<double>("importe_solicitado")
                        .HasColumnType("double precision");

                    b.Property<double>("saldo_categoria")
                        .HasColumnType("double precision");

                    b.Property<int>("solicitudId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("categoriaId");

                    b.HasIndex("solicitudId");

                    b.ToTable("certificacionPresupuestarias");
                });

            modelBuilder.Entity("siapv_backend.Models.Correlativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("correlativo")
                        .HasColumnType("integer");

                    b.Property<int>("gestion")
                        .HasColumnType("integer");

                    b.Property<int>("procesointernoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("correlativos");
                });

            modelBuilder.Entity("siapv_backend.Models.EstadoSolicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("estadoSolicitudes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            estado = "Designado"
                        },
                        new
                        {
                            Id = 2,
                            estado = "Solitado"
                        },
                        new
                        {
                            Id = 3,
                            estado = "Pendiente"
                        },
                        new
                        {
                            Id = 4,
                            estado = "Enviado a revisión"
                        },
                        new
                        {
                            Id = 5,
                            estado = "Aprobado"
                        },
                        new
                        {
                            Id = 6,
                            estado = "Finalizado"
                        });
                });

            modelBuilder.Entity("siapv_backend.Models.FuenteFinanciamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("codigo_fuente")
                        .HasColumnType("integer");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("literal")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("fuenteFinanciamientos");
                });

            modelBuilder.Entity("siapv_backend.Models.LugarDestino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("destino")
                        .IsRequired()
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("lugarDestinos");
                });

            modelBuilder.Entity("siapv_backend.Models.MediosTransporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("transporte")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.ToTable("mediosTransportes");
                });

            modelBuilder.Entity("siapv_backend.Models.OperacionPOA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("activo")
                        .HasColumnType("boolean");

                    b.Property<string>("codigo_op")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("fuente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nombre_operacion")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("prog")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("proyecto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("operacionPOAs");
                });

            modelBuilder.Entity("siapv_backend.Models.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("proyectos");
                });

            modelBuilder.Entity("siapv_backend.Models.Reprogramacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("createAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("destinoId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("fecha_emsision")
                        .HasColumnType("date");

                    b.Property<double>("importe")
                        .HasColumnType("double precision");

                    b.Property<string>("justificacion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("linea")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("nro_boleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("origenId")
                        .HasColumnType("integer");

                    b.Property<int>("solicitudId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("destinoId");

                    b.HasIndex("origenId");

                    b.HasIndex("solicitudId");

                    b.ToTable("reprogramaciones");
                });

            modelBuilder.Entity("siapv_backend.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.HasKey("Id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("siapv_backend.Models.SolicitudViaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("citeId")
                        .HasColumnType("integer");

                    b.Property<string>("cite_memo")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("descripcion_viaje")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("designadorId")
                        .HasColumnType("integer");

                    b.Property<int>("empleadoId")
                        .HasColumnType("integer");

                    b.Property<int?>("estadoId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("fechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("fechaInicio")
                        .HasColumnType("date");

                    b.Property<int>("fuenteId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly?>("horaFin")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("horaInicio")
                        .HasColumnType("time without time zone");

                    b.Property<int>("lugarDestinoId")
                        .HasColumnType("integer");

                    b.Property<int?>("lugarOrigenId")
                        .HasColumnType("integer");

                    b.Property<int>("proyectoId")
                        .HasColumnType("integer");

                    b.Property<int?>("tipoViajeId")
                        .HasColumnType("integer");

                    b.Property<int?>("transporteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("citeId");

                    b.HasIndex("estadoId");

                    b.HasIndex("fuenteId");

                    b.HasIndex("lugarDestinoId");

                    b.HasIndex("lugarOrigenId");

                    b.HasIndex("proyectoId");

                    b.HasIndex("tipoViajeId");

                    b.HasIndex("transporteId");

                    b.ToTable("solicitudViajes");
                });

            modelBuilder.Entity("siapv_backend.Models.TipoViaje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("monto_viatico")
                        .HasColumnType("double precision");

                    b.Property<string>("tipo")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("tiposViaje");
                });

            modelBuilder.Entity("siapv_backend.Models.userRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("empleadoId")
                        .HasColumnType("integer");

                    b.Property<int>("personaId")
                        .HasColumnType("integer");

                    b.Property<int>("roleId")
                        .HasColumnType("integer");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("roleId");

                    b.ToTable("userRoles");
                });

            modelBuilder.Entity("siapv_backend.Models.CertificacionPOA", b =>
                {
                    b.HasOne("siapv_backend.Models.ActividadPOA", "actividadAcp")
                        .WithMany()
                        .HasForeignKey("actividadAcpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("siapv_backend.Models.ActividadPOA", "actividadAmp")
                        .WithMany()
                        .HasForeignKey("actividadAmpId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("siapv_backend.Models.SolicitudViaje", "solicitud")
                        .WithMany()
                        .HasForeignKey("solicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("actividadAcp");

                    b.Navigation("actividadAmp");

                    b.Navigation("solicitud");
                });

            modelBuilder.Entity("siapv_backend.Models.CertificacionPresupuestaria", b =>
                {
                    b.HasOne("siapv_backend.Models.CategoriaProgramatica", "categoria")
                        .WithMany()
                        .HasForeignKey("categoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("siapv_backend.Models.SolicitudViaje", "solicitud")
                        .WithMany()
                        .HasForeignKey("solicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoria");

                    b.Navigation("solicitud");
                });

            modelBuilder.Entity("siapv_backend.Models.Reprogramacion", b =>
                {
                    b.HasOne("siapv_backend.Models.LugarDestino", "destino")
                        .WithMany()
                        .HasForeignKey("destinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("siapv_backend.Models.LugarDestino", "origen")
                        .WithMany()
                        .HasForeignKey("origenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("siapv_backend.Models.SolicitudViaje", "solicitud")
                        .WithMany()
                        .HasForeignKey("solicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("destino");

                    b.Navigation("origen");

                    b.Navigation("solicitud");
                });

            modelBuilder.Entity("siapv_backend.Models.SolicitudViaje", b =>
                {
                    b.HasOne("siapv_backend.DocGenerado", "cite")
                        .WithMany()
                        .HasForeignKey("citeId");

                    b.HasOne("siapv_backend.Models.EstadoSolicitud", "estado")
                        .WithMany()
                        .HasForeignKey("estadoId");

                    b.HasOne("siapv_backend.Models.FuenteFinanciamiento", "fuente")
                        .WithMany()
                        .HasForeignKey("fuenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("siapv_backend.Models.LugarDestino", "lugarDestino")
                        .WithMany()
                        .HasForeignKey("lugarDestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("siapv_backend.Models.LugarDestino", "lugarOrigen")
                        .WithMany()
                        .HasForeignKey("lugarOrigenId");

                    b.HasOne("siapv_backend.Models.Proyecto", "proyecto")
                        .WithMany()
                        .HasForeignKey("proyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("siapv_backend.Models.TipoViaje", "tipoViaje")
                        .WithMany()
                        .HasForeignKey("tipoViajeId");

                    b.HasOne("siapv_backend.Models.MediosTransporte", "transporte")
                        .WithMany()
                        .HasForeignKey("transporteId");

                    b.Navigation("cite");

                    b.Navigation("estado");

                    b.Navigation("fuente");

                    b.Navigation("lugarDestino");

                    b.Navigation("lugarOrigen");

                    b.Navigation("proyecto");

                    b.Navigation("tipoViaje");

                    b.Navigation("transporte");
                });

            modelBuilder.Entity("siapv_backend.Models.userRole", b =>
                {
                    b.HasOne("siapv_backend.Models.Role", "role")
                        .WithMany()
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");
                });
#pragma warning restore 612, 618
        }
    }
}
